### ISSUE TITLE
How the hell do we get this now?

### ISSUE THREAD

**Issue by jrubimf** [Scottishdwarf/CloudMagicRotations#4]
Discord is down for a second time.

**Comment by twxio** [comment]
is there a new discord channel or a new slack channel or something like that?

**Comment by Gandalf15net** [comment]
Just realised too that discord is gone?

**Comment by JMBnet** [comment]
I have no idea how to get a hold of him, anybody have him as a friend on discord?  But yeah, his discord was there one day and the next day, it was gone and this was a few weeks ago as well.

**Comment by smartie1983** [comment]
https://join.slack.com/t/cloudy-home/shared_invite/enQtMzI5MDE3ODk3NzYxLTFkMzRlZjMyMTNjMTAzYWRjYzk2NmRmM2I0NWY3NmMxYjQ5ZmU4ODE1OWE2MWUzMTRjNmZlOWZlMGNhNmM1Y2M - thats the new slack server
